name: A9 Camera fake server
version: 2.4
slug: a9-cam
description: A9 Cam fake server
url: https://github.com/niruse/a9-camera-ha-add-on
advanced: true
startup: application
init: false
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
host_network: true
ports:
  6123/tcp: 6123
  80/tcp: 80
  6123/udp: 6123
